GET http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluYmF0bWFuIiwidXNlcklEIjoyMywiaXNfYWRtaW4iOnRydWUsImV4cCI6MTc2ODM3ODUxOX0.WQbTxoGAChymGHW9wxbbj778-RstQ3v1aKunbLFeCdo