GET http://localhost:8080/jobs/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNreXkxIiwidXNlcklEIjoxLCJpc19hZG1pbiI6ZmFsc2UsImV4cCI6MTc2ODI0NzI5N30.gy5Bhu2zH89ekbStQRlxk8o8dJwNVKKsGyMWXvNXhbk